name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  redux: ^5.0.0
  day: ^0.8.0
  flutter_easyrefresh: ^2.2.1
  shared_preferences: ^2.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets begin
    # images/*
    - images/406.png
    - images/bg400.png
    - images/bg401.png
    - images/407.png
    - images/405.png
    - images/bg403.png
    - images/bg402.png
    - images/410.png
    - images/404.png
    - images/400.png
    - images/399.png
    - images/icon_back.png
    - images/401.png
    - images/403.png
    - images/bg405.png
    - images/bg404.png
    - images/402.png
    - images/317.png
    - images/303.png
    - images/bg503.png
    - images/101.png
    - images/511.png
    - images/bg305.png
    - images/bg304.png
    - images/510.png
    - images/504.png
    - images/100.png
    - images/bg502.png
    - images/302.png
    - images/316.png
    - images/300.png
    - images/314.png
    - images/499.png
    - images/bg500.png
    - images/102.png
    - images/bg104.png
    - images/512.png
    - images/bg306.png
    - images/bg307.png
    - images/507.png
    - images/513.png
    - images/103.png
    - images/bg501.png
    - images/315.png
    - images/301.png
    - images/305.png
    - images/311.png
    - images/bg101.png
    - images/503.png
    - images/bg303.png
    - images/bg302.png
    - images/502.png
    - images/bg100.png
    - images/bg504.png
    - images/310.png
    - images/304.png
    - images/312.png
    - images/306.png
    - images/104.png
    - images/bg102.png
    - images/500.png
    - images/514.png
    - images/bg300.png
    - images/bg301.png
    - images/515.png
    - images/501.png
    - images/bg103.png
    - images/bg507.png
    - images/307.png
    - images/313.png
    - images/901.png
    - images/900.png
    - images/309.png
    - images/bg509.png
    - images/308.png
    - images/456.png
    - images/318.png
    - images/bg901.png
    - images/bg900.png
    - images/457.png
    - images/509.png
    - images/bg309.png
    - images/bg308.png
    - images/508.png
    - images/802.png
    - images/bg804.png
    - images/bg151.png
    - images/bg150.png
    - images/bg805.png
    - images/803.png
    - images/801.png
    - images/bg152.png
    - images/bg153.png
    - images/bg999.png
    - images/800.png
    - images/409.png
    - images/151.png
    - images/804.png
    - images/805.png
    - images/150.png
    - images/408.png
    - images/350.png
    - images/152.png
    - images/807.png
    - images/bg801.png
    - images/bg154.png
    - images/bg800.png
    - images/999.png
    - images/806.png
    - images/153.png
    - images/351.png
    # assets end
